# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1-snapshot-9
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version = 26.1
maven_group = baphomethlabs.fortytwoedit
archives_base_name = 42edit